pipelines:
  - name: "corrected-nested-csv-example"
    enabled: true
    interval: "30s"
    
    extract:
      elasticsearch_query: |
        {
          "size": 0,
          "aggs": {
            "services": {
              "terms": {
                "field": "service.keyword",
                "size": 10
              },
              "aggs": {
                "doc_count": {
                  "value_count": {
                    "field": "_id"
                  }
                },
                "avg_response_time": {
                  "avg": {
                    "field": "response_time"
                  }
                },
                "hosts": {
                  "terms": {
                    "field": "host.keyword",
                    "size": 5
                  },
                  "aggs": {
                    "cpu_usage": {
                      "terms": {
                        "field": "cpu_type.keyword",
                        "size": 3
                      },
                      "aggs": {
                        "system": {
                          "avg": {
                            "field": "cpu.system"
                          }
                        },
                        "user": {
                          "avg": {
                            "field": "cpu.user"
                          }
                        },
                        "idle": {
                          "avg": {
                            "field": "cpu.idle"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      urls:
        - "https://elasticsearch.example.com:9200/metrics-*/_search"
      cluster_names:
        - "production-cluster"
      auth_headers:
        - "ApiKey ${ELASTICSEARCH_API_KEY}"
      json_path: "aggregations.services.buckets"
      interval: "30s"
      timeout: "10s"
      max_retries: 3
      
    transform:
      stateless: true
      substitute_zeros_for_null: true
      previous_results_sets: 0
      output_format: "csv"  # Enable CSV output format with corrected logic
      conversion_functions:
        - field: "avg_response_time"
          function: "convert_type"
          from_type: "float"
          to_type: "float"
        - field: "doc_count"
          function: "convert_type"
          from_type: "float"
          to_type: "int"
          
    load:
      streams:
        - type: "csv"
          config:
            path: "/tmp/elasticetl/corrected-nested-output"
          labels:
            pipeline: "corrected-nested-csv-example"
            
        - type: "debug"
          config:
            path: "/tmp/elasticetl/debug/corrected-nested"
          labels:
            pipeline: "corrected-nested-csv-example"

global:
  resource_limits:
    max_memory_mb: 512
    max_cpu_percent: 50
    max_goroutines: 100
    max_connections: 10
  metrics:
    enabled: true
    port: 8080
    path: "/metrics"
    interval: "30s"
  logging:
    level: "info"
    format: "json"
    output: "stdout"
